language: c

sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

os:
  - linux
  - osx

before_script:
  - pip install --user hererocks
  - hererocks env --$LUA
  - export PATH="$PWD/env/bin:$PATH"

script:
  - cmake .
  - make
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
