language: c

sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

os:
  - linux

matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate

install:
  - pip install --user hererocks
  - hererocks env --$LUA
  - export PATH="$PWD/env/bin:$PWD/env:$PATH"

script:
  - cmake .
  - make
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
